//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanionUI.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CompanionUI.Resources.Localization.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string education_intrigue_1 {
            get {
                return ResourceManager.GetString("education_intrigue_1", resourceCulture);
            }
        }
        
        internal static string education_intrigue_2 {
            get {
                return ResourceManager.GetString("education_intrigue_2", resourceCulture);
            }
        }
        
        internal static string education_intrigue_3 {
            get {
                return ResourceManager.GetString("education_intrigue_3", resourceCulture);
            }
        }
        
        internal static string education_intrigue_4 {
            get {
                return ResourceManager.GetString("education_intrigue_4", resourceCulture);
            }
        }
        
        internal static string education_intrigue_5 {
            get {
                return ResourceManager.GetString("education_intrigue_5", resourceCulture);
            }
        }
        
        internal static string education_diplomacy_1 {
            get {
                return ResourceManager.GetString("education_diplomacy_1", resourceCulture);
            }
        }
        
        internal static string education_diplomacy_2 {
            get {
                return ResourceManager.GetString("education_diplomacy_2", resourceCulture);
            }
        }
        
        internal static string education_diplomacy_3 {
            get {
                return ResourceManager.GetString("education_diplomacy_3", resourceCulture);
            }
        }
        
        internal static string education_diplomacy_4 {
            get {
                return ResourceManager.GetString("education_diplomacy_4", resourceCulture);
            }
        }
        
        internal static string education_diplomacy_5 {
            get {
                return ResourceManager.GetString("education_diplomacy_5", resourceCulture);
            }
        }
        
        internal static string education_stewardship_1 {
            get {
                return ResourceManager.GetString("education_stewardship_1", resourceCulture);
            }
        }
        
        internal static string education_stewardship_2 {
            get {
                return ResourceManager.GetString("education_stewardship_2", resourceCulture);
            }
        }
        
        internal static string education_stewardship_3 {
            get {
                return ResourceManager.GetString("education_stewardship_3", resourceCulture);
            }
        }
        
        internal static string education_stewardship_4 {
            get {
                return ResourceManager.GetString("education_stewardship_4", resourceCulture);
            }
        }
        
        internal static string education_stewardship_5 {
            get {
                return ResourceManager.GetString("education_stewardship_5", resourceCulture);
            }
        }
        
        internal static string education_martial_1 {
            get {
                return ResourceManager.GetString("education_martial_1", resourceCulture);
            }
        }
        
        internal static string education_martial_2 {
            get {
                return ResourceManager.GetString("education_martial_2", resourceCulture);
            }
        }
        
        internal static string education_martial_3 {
            get {
                return ResourceManager.GetString("education_martial_3", resourceCulture);
            }
        }
        
        internal static string education_martial_4 {
            get {
                return ResourceManager.GetString("education_martial_4", resourceCulture);
            }
        }
        
        internal static string education_martial_5 {
            get {
                return ResourceManager.GetString("education_martial_5", resourceCulture);
            }
        }
        
        internal static string education_learning_1 {
            get {
                return ResourceManager.GetString("education_learning_1", resourceCulture);
            }
        }
        
        internal static string education_learning_2 {
            get {
                return ResourceManager.GetString("education_learning_2", resourceCulture);
            }
        }
        
        internal static string education_learning_3 {
            get {
                return ResourceManager.GetString("education_learning_3", resourceCulture);
            }
        }
        
        internal static string education_learning_4 {
            get {
                return ResourceManager.GetString("education_learning_4", resourceCulture);
            }
        }
        
        internal static string education_learning_5 {
            get {
                return ResourceManager.GetString("education_learning_5", resourceCulture);
            }
        }
        
        internal static string lustful {
            get {
                return ResourceManager.GetString("lustful", resourceCulture);
            }
        }
        
        internal static string chaste {
            get {
                return ResourceManager.GetString("chaste", resourceCulture);
            }
        }
        
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string gluttonous {
            get {
                return ResourceManager.GetString("gluttonous", resourceCulture);
            }
        }
        
        internal static string temperate {
            get {
                return ResourceManager.GetString("temperate", resourceCulture);
            }
        }
        
        internal static string greedy {
            get {
                return ResourceManager.GetString("greedy", resourceCulture);
            }
        }
        
        internal static string generous {
            get {
                return ResourceManager.GetString("generous", resourceCulture);
            }
        }
        
        internal static string lazy {
            get {
                return ResourceManager.GetString("lazy", resourceCulture);
            }
        }
        
        internal static string diligent {
            get {
                return ResourceManager.GetString("diligent", resourceCulture);
            }
        }
        
        internal static string wrathful {
            get {
                return ResourceManager.GetString("wrathful", resourceCulture);
            }
        }
        
        internal static string calm {
            get {
                return ResourceManager.GetString("calm", resourceCulture);
            }
        }
        
        internal static string patient {
            get {
                return ResourceManager.GetString("patient", resourceCulture);
            }
        }
        
        internal static string impatient {
            get {
                return ResourceManager.GetString("impatient", resourceCulture);
            }
        }
        
        internal static string arrogant {
            get {
                return ResourceManager.GetString("arrogant", resourceCulture);
            }
        }
        
        internal static string humble {
            get {
                return ResourceManager.GetString("humble", resourceCulture);
            }
        }
        
        internal static string deceitful {
            get {
                return ResourceManager.GetString("deceitful", resourceCulture);
            }
        }
        
        internal static string honest {
            get {
                return ResourceManager.GetString("honest", resourceCulture);
            }
        }
        
        internal static string craven {
            get {
                return ResourceManager.GetString("craven", resourceCulture);
            }
        }
        
        internal static string brave {
            get {
                return ResourceManager.GetString("brave", resourceCulture);
            }
        }
        
        internal static string shy {
            get {
                return ResourceManager.GetString("shy", resourceCulture);
            }
        }
        
        internal static string gregarious {
            get {
                return ResourceManager.GetString("gregarious", resourceCulture);
            }
        }
        
        internal static string ambitious {
            get {
                return ResourceManager.GetString("ambitious", resourceCulture);
            }
        }
        
        internal static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        internal static string arbitrary {
            get {
                return ResourceManager.GetString("arbitrary", resourceCulture);
            }
        }
        
        internal static string just {
            get {
                return ResourceManager.GetString("just", resourceCulture);
            }
        }
        
        internal static string cynical {
            get {
                return ResourceManager.GetString("cynical", resourceCulture);
            }
        }
        
        internal static string zealous {
            get {
                return ResourceManager.GetString("zealous", resourceCulture);
            }
        }
        
        internal static string paranoid {
            get {
                return ResourceManager.GetString("paranoid", resourceCulture);
            }
        }
        
        internal static string trusting {
            get {
                return ResourceManager.GetString("trusting", resourceCulture);
            }
        }
        
        internal static string compassionate {
            get {
                return ResourceManager.GetString("compassionate", resourceCulture);
            }
        }
        
        internal static string callous {
            get {
                return ResourceManager.GetString("callous", resourceCulture);
            }
        }
        
        internal static string sadistic {
            get {
                return ResourceManager.GetString("sadistic", resourceCulture);
            }
        }
        
        internal static string stubborn {
            get {
                return ResourceManager.GetString("stubborn", resourceCulture);
            }
        }
        
        internal static string fickle {
            get {
                return ResourceManager.GetString("fickle", resourceCulture);
            }
        }
        
        internal static string eccentric {
            get {
                return ResourceManager.GetString("eccentric", resourceCulture);
            }
        }
        
        internal static string vengeful {
            get {
                return ResourceManager.GetString("vengeful", resourceCulture);
            }
        }
    }
}
